name: Lan Huynh
favicon: null
layout_spectrum: 0.5985026331618428
typography_spectrum: 0.03345766942948103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.21886605536565185
  lightness: 0.9975184490904212
  saturation: 0.21630623005330563
  rhythmicContrast: 0.043265425600111485
purpose: []
